# -*- coding: utf-8 -*-
"""Buoi10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aJ0ZotYzxalhm-yzwXnMeyPSw2tueXDA
"""

#w8a1
a, b = map(int, input().split())
try:
   print((f"{(a/b):.2f}"))
except:
  if b == 0:
    print("Loi chia khong")

#w8a2
n = int(input())
my_list = list(map(int, input().split()))

try:
    print(my_list[n])
except:
    print("Loi truy cap chi so")

try:
    a = int(input())
    if a <= 0:
        print("Khong phai so nguyen duong")
    else:
        seen = set()
        while a != 1:
            if a in seen:
                print("NO")
                break
            seen.add(a)
            a = sum(int(d)**2 for d in str(a))
        if a == 1:
            print("YES")
except ValueError:
    print("Loi nhap lieu")

#w8a4
try:
  a,b = map(int, input().split())
except:
  print("sai kieu")
else:
  print(a+b)
finally:
  print("ket thuc chuong trinh")

#w8a5
n = input()
danh_sach = []
chk = False
for i in n:
  try:
    danh_sach.append(int(i))
  except:
    chk = True
print(*danh_sach)
if chk:
  print("canh bao")

#w10a6
import math
a = int(input())
try:
  x = math.sqrt(a)
  print(f"{x:.2f}")
except:
    print("So am")

#w10a8
try:
  nam_sinh = input()
  tuoi = 2025 - int(nam_sinh)
  if tuoi < 0:
    print("tuoi khong hop le")
  else:
    print(tuoi)
except:
  print("tuoi khong hop le")

#w10a8
try:
  a = input()
  list = a.lower()
  if list.endswith(".txt") or list.endswith("zip"):
      print("Doc file thanh cong")
  else:
    raise ValueError
except ValueError:
  print("File khong hop le")

#w10a9
try:
  a = input('')
  print(int(a))
except:
  print("Chuoi khong hop le")

#w10a10
try:
  n = int(input())
  list1 = list(map(int, input().split()))
  if len(list1) != len(set(list1)):
    raise ValueError
  print(sum(list1 ))
except ValueError:
  print("Mang khong hop le")

#w8a11

def f(n):
    if n == 0:
        return 0
    return f(n-1) * 2 + 1

print(f(3))