# -*- coding: utf-8 -*-
"""buoi3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179cA6G6EYLIrEkgmR6FzM9elW3PV-y2q
"""

n = int(input())
print(str(n)[::-1])

a, b = map(int, input().split())
a = a ^ b
b = a ^ b
a = a ^ b
print(a, b)

n = int(input())
if n > 0 and (n & (n - 1)) == 0:
    print("True")
else:
    print("False")

m, n = map(int, input().split())
print(m // n)

m, n = map(int, input().split())
print(-(-m // n))

x = int(input())
if x % 2 == 0:
    print("Even")
else:
    print("Odd")

a, b = map(int, input().split())
if a < 0 and b < 0:
    print("Yes")
else:
    print("No")

a = input()
b = input()
if len(a) > len(b):
    print("True")
else:
    print("False")

a = int(input())
b = int(input())
c = int(input())
if a + b > c and a + c > b and b + c > a:
    print("Yes")
else:
    print("No")

a = int(input())
b = int(input())
c = int(input())
d = int(input())
print(max(a, b, c, d))

a, b, c = map(int, input().split())
if a <= 0 or b <= 0 or c <= 0 or a + b <= c or a + c <= b or b + c <= a:
    print("Không phải tam giác")
elif a == b == c:
    print("Tam giác đều")
elif a == b or a == c or b == c:
    print("Tam giác cân")
else:
    print("Tam giác thường")

n = int(input())
if (n % 4 == 0 and n % 100 != 0) or (n % 400 == 0):
    print("Yes")
else:
    print("No")

kwh = int(input())
if kwh <= 50:
    total = kwh * 1500
elif kwh <= 100:
    total = 50 * 1500 + (kwh - 50) * 2000
else:
    total = 50 * 1500 + 50 * 2000 + (kwh - 100) * 3000
print(total)

a = float(input())
b = float(input())
if a == 0 and b == 0:
    print("Vô số nghiệm")
elif a == 0:
    print("Vô nghiệm")
else:
    x = -b / a
    print(f"{x:.2f}")

avg = float(input())
if avg >= 8.0:
    print("Giỏi")
elif avg >= 6.5:
    print("Khá")
elif avg >= 5.0:
    print("Trung bình")
else:
    print("Yếu")

x = float(input())
if x >= 0:
    tron_len = int(x) if x == int(x) else int(x) + 1
    tron_xuong = int(x)
else:
    tron_len = int(x)
    tron_xuong = int(x) if x == int(x) else int(x) - 1
if x >= 0:
    gan_nhat = int(x + 0.5)
else:
    gan_nhat = int(x - 0.5)
print(tron_len, tron_xuong, gan_nhat)

a, b, c = map(int, input().split())
if a <= 0 or b <= 0 or c <= 0 or a + b <= c or a + c <= b or b + c <= a:
    print("Không phải tam giác")
elif a == b == c:
    print("Tam giác đều")
elif a == b or a == c or b == c:
    print("Tam giác cân")
else:
    print("Tam giác thường")