# -*- coding: utf-8 -*-
"""buoi4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aC-lEADWjdjRQssX0pQvWh2rxUXGuQR
"""

n = int(input())
s = 0
for i in range(1, n + 1):
    s += i
print(s)

while True:
    n = int(input())
    if n > 0:
        break
if n < 2:
    print("False")
else:
    prime = True
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            prime = False
            break
    print("True" if prime else "False")

n = int(input())
res = 1
for i in range(1, n + 1):
    res *= i
print(res)

n = int(input())
n = abs(n)
count = 0
if n == 0:
    count = 1
else:
    while n > 0:
        count += 1
        n //= 10
print(count)

n = int(input())
arr = []
numbers = input().split()
for i in range(n):
    arr.append(int(numbers[i]))
found = False
for i in range(n):
    if arr[i] == 42:
        found = True
        break
if found == True:
    print("I've found the meaning of life!")
else:
    print("It's a joke!")

a, b = map(int, input().split())
def is_prime(x):
    if x < 2:
        return False
    for i in range(2, int(x ** 0.5) + 1):
        if x % i == 0:
            return False
    return True
s = 0
for i in range(a, b + 1):
    if is_prime(i):
        s += i
print(s)

n = int(input())
max_pf = -1
i = 2
while i * i <= n:
    while n % i == 0:
        max_pf = i
        n //= i
    i += 1
if n > 1:
    max_pf = n
print(max_pf)

def is_palindrome(x):
    return str(x) == str(x)[::-1]
n = int(input())
steps = 0
while not is_palindrome(n):
    rev = int(str(n)[::-1])
    n += rev
    steps += 1
print(steps, n)

n = int(input())
res = []
i = 1
while i * i <= n:
    sq = i * i
    s = str(sq)
    if len(set(s)) == len(s):
        res.append(str(sq))
    i += 1
if res:
    print(" ".join(res))
else:
    print("(no number)")

n = int(input())
def collatz_len(x):
    length = 1
    while x != 1:
        if x % 2 == 0:
            x //= 2
        else:
            x = 3 * x + 1
        length += 1
    return length
max_len = 0
number = 1
for i in range(1, n + 1):
    l = collatz_len(i)
    if l > max_len:
        max_len = l
        number = i

print(number, max_len)

n = int(input())
count = 0
for i in range(1, int(n ** 0.5) + 1):
    if n % i == 0:
        if i % 2 == 0:
            count += 1
        if i != n // i and (n // i) % 2 == 0:
            count += 1
print(count)

x, n = map(int, input().split())
rate = 0.007
for _ in range(n):
    x += x * rate
print(int(x))

a, b = map(int, input().split())
def sum_divisors(n):
    s = 1
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            s += i
            if i != n // i:
                s += n // i
    return s if n != 1 else 0
if sum_divisors(a) == b and sum_divisors(b) == a:
    print("true")
else:
    print("false")

import math
m, n = map(int, input().split())
print(math.gcd(m, n))

total, legs = map(int, input().split())
found = False
for chicken in range(total + 1):
    dog = total - chicken
    if 2 * chicken + 4 * dog == legs:
        print(chicken, dog)
        found = True
        break
if not found:
    print("invalid")

for i in range(1, 100):
    if i % 2 == 0 and i % 3 == 0:
        print(i, end=" ")

a = int(input())

for i in range(1, 11):
    print(a, "x", i, "=", a * i)

a = int(input())

for i in range(1, 11):
    print(a, "x", i, "=", a * i)

n = int(input())
for i in range(1, n + 1):
    if i % 2 == 0:
        print(i, end=" ")

n = int(input())
if n > 0 and (n & (n - 1)) == 0:
    print("True")
else:
    print("False")

n = int(input())
s = 0
while n > 0:
    s += n % 10
    n //= 10

print(s)

n = int(input())
even = 0
odd = 0
while n > 0:
    d = n % 10
    if d % 2 == 0:
        even += 1
    else:
        odd += 1
    n //= 10
print(even, odd)

n = int(input())
k = 0
s = 0
while s + (k + 1) < n:
    k += 1
    s += k
print(k)

A = float(input())
n = 0
s = 0.0
while s <= A:
    n += 1
    s += 1 / n
print(n)

numbers = []
while True:
    x = int(input())
    if x == -1:
        break
    numbers.append(x)
if len(numbers) > 0:
    print(max(numbers), min(numbers))

A = int(input())
a = 1
b = 1
while b <= A:
    temp = a + b
    a = b
    b = temp
print(a)

s = input()
count = 0
in_word = False
for i in range(0, len(s)):
    if s[i] != " " and not in_word:
        count += 1
        in_word = True
    if s[i] == " ":
        in_word = False
print(count)

s = input()
word = ""
for i in range(0, len(s)):
    if s[i] == " ":
        break
    word += s[i]
print(word)

s = input()
num = ""
total = 0
for i in range(len(s)):
    if s[i] != ",":
        num += s[i]
    else:
        total += int(num.strip())
        num = ""
total += int(num.strip())
print("Tổng:", total)

s = input()
upper = 0
lower = 0
digit = 0
for i in range(len(s)):
    if 'A' <= s[i] <= 'Z':
        upper += 1
    elif 'a' <= s[i] <= 'z':
        lower += 1
    elif '0' <= s[i] <= '9':
        digit += 1
print(upper, lower, digit)

s = input()
total = 0
for i in range(len(s)):
    if '0' <= s[i] <= '9':
        total += int(s[i])

print(total)

s = input()
upper = False
lower = False
digit = False
special = False
for i in range(len(s)):
    if 'A' <= s[i] <= 'Z':
        upper = True
    elif 'a' <= s[i] <= 'z':
        lower = True
    elif '0' <= s[i] <= '9':
        digit = True
    else:
        special = True
if upper and lower and digit and special and len(s) > 6:
    print("Strong")
else:
    print("Weak")

n = input()
res = ""
count = 0
for i in range(len(n) - 1, -1, -1):
    res = n[i] + res
    count += 1
    if count == 3 and i != 0:
        res = "." + res
        count = 0
print(res)

a = input()
b = input()
result = ""
i = 0
while i < len(a):
    match = True
    for j in range(len(b)):
        if i + j >= len(a) or a[i + j] != b[j]:
            match = False
            break
    if match:
        i += len(b)
    else:
        result += a[i]
        i += 1
print(result)