# -*- coding: utf-8 -*-
"""buoi5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1teVgXN9Up6gNO2ybTOKSSy5DXnz3AS0H
"""

def Max_Of_Two(a, b) -> int:
    if a > b:
        return a
    else:
        return b

def swap(a, b):
    temp = a
    a = b
    b = temp
    return a, b

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

def is_perfect(n):
    if n <= 1:
        return False
    total = 0
    for i in range(1, n):
        if n % i == 0:
            total = total + i
    if total == n:
        return True
    else:
        return False

def find_first(arr, k):
    i = 0
    while i < len(arr):
        if arr[i] == k:
            return i
        i = i + 1
    return -1

def factorial(n):
    result = 1
    i = 1
    while i <= n:
        result = result * i
        i = i + 1
    return result



def calculator(num1, operat, num2):
    if operat == "+":
        result = num1 + num2
    elif operat == "-":
        result = num1 - num2
    elif operat == "*":
        result = num1 * num2
    elif operat == "/":
        result = num1 / num2
    else:
        return None
    return round(result, 2)

def hamming_distance(x, y):
    xor = x ^ y
    count = 0
    while xor > 0:
        if xor % 2 == 1:
            count = count + 1
        xor = xor // 2
    return count

def sum_digits(n):
    if n < 0:
        n = -n
    total = 0
    while n > 0:
        digit = n % 10
        total = total + digit
        n = n // 10
    return total

def sum_digits(n):
    if n < 0:
        n = -n
    total = 0
    while n > 0:
        digit = n % 10
        total = total + digit
        n = n // 10
    return total

def is_isomorphic(a, b):
    dict1 = {}
    dict2 = {}
    i = 0
    while i < len(a):
        ch1 = a[i]
        ch2 = b[i]

        if ch1 in dict1:
            if dict1[ch1] != ch2:
                return False
        else:
            dict1[ch1] = ch2

        if ch2 in dict2:
            if dict2[ch2] != ch1:
                return False
        else:
            dict2[ch2] = ch1

        i = i + 1
    return True