# -*- coding: utf-8 -*-
"""buổi 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DeFh3WJo665gl6dwxRezKsU5PjPTe6t
"""

nums = list(map(int, input().split()))
result = []
for i in range(len(nums)):
    if nums[i] not in result:
        result.append(nums[i])
print(result)

nums = list(map(int, input().split()))
result = []
total = 0
for i in range(len(nums)):
    total = total + nums[i]
    result.append(total)
print(result)

t = tuple(map(int, input().split()))
k = int(input())
n = len(t)
if n > 0:
    k = k % n
new_tuple = ()
for i in range(k, n):
    new_tuple = new_tuple + (t[i],)
for i in range(0, k):
    new_tuple = new_tuple + (t[i],)
print(new_tuple)

pairs = input().split()
d = {}
for item in pairs:
    if ":" in item:
        parts = item.split(":")
        if len(parts) == 2:
            key = parts[0]
            value = parts[1]
            if key in d:
                d[key].append(value)
            else:
                d[key] = [value]
print(d)

nums = list(map(int, input().split()))
pos = 0
neg = 0
zero = 0
for i in range(len(nums)):
    if nums[i] > 0:
        pos = pos + 1
    elif nums[i] < 0:
        neg = neg + 1
    else:
        zero = zero + 1
result = {
    'positives': pos,
    'negatives': neg,
    'zeros': zero
}
print(result)

nums = list(map(int, input().split()))
total = 0
for i in range(len(nums)):
    total = total + nums[i]
print(total)

t = tuple(input().split())
if len(t) > 0:
    first = t[0]
    last = t[len(t) - 1]
else:
    first = None
    last = None
rev = ()
for i in range(len(t) - 1, -1, -1):
    rev = rev + (t[i],)
print(first, last, rev)

words = input().split()
d = {}
for i in range(len(words)):
    w = words[i]
    if w in d:
        d[w] = d[w] + 1
    else:
        d[w] = 1
print(d)

d1 = eval(input())
d2 = eval(input())
result = {}
for key in d1:
    result[key] = d1[key]
for key in d2:
    if key in result:
        result[key] = result[key] + d2[key]
    else:
        result[key] = d2[key]
sorted_keys = sorted(result.keys())
new_dict = {}
for key in sorted_keys:
    new_dict[key] = result[key]
print(new_dict)

nums = list(map(int, input().split()))
k = int(input())
result = []
for i in range(len(nums)):
    for j in range(i + 1, len(nums)):
        if nums[i] + nums[j] == k:
            pair = (nums[i], nums[j])
            if pair not in result:
                result.append(pair)
result.sort()
print(result)

t = tuple(map(int, input().split()))
even = ()
odd = ()
for i in range(len(t)):
    if t[i] % 2 == 0:
        even = even + (t[i],)
    else:
        odd = odd + (t[i],)
print(even)
print(odd)

nums = list(map(int, input().split()))
d = {}
for i in range(len(nums)):
    if nums[i] in d:
        d[nums[i]] = d[nums[i]] + 1
    else:
        d[nums[i]] = 1
max_count = 0
answer = None
for key in d:
    if d[key] > max_count:
        max_count = d[key]
        answer = key
    elif d[key] == max_count:
        if key < answer:
            answer = key
print(answer)

items = input().split()
d = {}
for i in range(0, len(items), 2):
    key = items[i]
    value = items[i + 1]
    d[value] = key
print(d)

list1 = list(map(int, input().split()))
list2 = list(map(int, input().split()))
result = []
for i in range(len(list1)):
    if list1[i] in list2 and list1[i] not in result:
        result.append(list1[i])
print(result)

items = input().split()
k = int(input())
d = {}
for i in range(0, len(items), 2):
    key = items[i]
    value = int(items[i + 1])
    d[key] = value
new_dict = {}
for key in d:
    if d[key] > k:
        new_dict[key] = d[key]
print(new_dict)

def find_max_index(arr):
    max_value = arr[0]
    max_index = 0
    for i in range(len(arr)):
        if arr[i] > max_value:
            max_value = arr[i]
            max_index = i
    return max_index

def find_first(arr, k):
    for i in range(len(arr)):
        if arr[i] == k:
            return i
    return -1

words = input().split()
d = {}
for i in range(len(words)):
    w = words[i]
    if w in d:
        d[w] = d[w] + (i,)
    else:
        d[w] = (i,)
print(d)

def find_max_index(arr):
    max_value = arr[0]
    max_index = 0
    for i in range(len(arr)):
        if arr[i] > max_value:
            max_value = arr[i]
            max_index = i
    return max_index