# -*- coding: utf-8 -*-
"""buổi9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8eQ0ffWsGC3YeWHYhKdolqD5T9oVfh2
"""

def merge(list1, list2):
    i = 0
    j = 0
    result = []

    while i < len(list1) and j < len(list2):
        if list1[i] <= list2[j]:
            result.append(list1[i])
            i += 1
        else:
            result.append(list2[j])
            j += 1

    while i < len(list1):
        result.append(list1[i])
        i += 1

    while j < len(list2):
        result.append(list2[j])
        j += 1

    return result

import heapq

n, m = map(int, input().split())

matrix = []
for i in range(n):
    row = list(map(int, input().split()))
    matrix.append(row)

k = int(input())

heap = []

for j in range(m):
    heapq.heappush(heap, (matrix[0][j], 0, j))

count = 0
result = 0

while heap:
    val, r, c = heapq.heappop(heap)
    count += 1

    if count == k:
        result = val
        break

    if r + 1 < n:
        heapq.heappush(heap, (matrix[r+1][c], r+1, c))

print(result)

s = input()
s = list(s)

min_num = int("".join(s))

n = len(s)

for i in range(n):
    for j in range(i+1, n):
        s[i], s[j] = s[j], s[i]

        if s[0] != '0':
            num = int("".join(s))
            if num < min_num:
                min_num = num

        s[i], s[j] = s[j], s[i]

print(min_num)

q = int(input())

for _ in range(q):
    a = input()
    b = input()

    i = 0
    j = 0

    while i < len(a) and j < len(b):
        if a[i].upper() == b[j]:
            j += 1
        i += 1

    if j == len(b):
        print("YES")
    else:
        print("NO")

list1 = list(map(int, input().split()))
list2 = list(map(int, input().split()))

n1 = len(list1)
n2 = len(list2)

found = False

for i in range(n2 - n1 + 1):
    if list2[i:i+n1] == list1:
        found = True
        break

if found:
    print("YES")
else:
    print("NO")

n = int(input())
arr = list(map(int, input().split()))

i = n - 2
while i >= 0 and arr[i] >= arr[i+1]:
    i -= 1

if i >= 0:
    j = n - 1
    while arr[j] <= arr[i]:
        j -= 1

    arr[i], arr[j] = arr[j], arr[i]

arr[i+1:] = reversed(arr[i+1:])

print(*arr)

def canPlaceFlowers(flowerbed, k):
    count = 0

    for i in range(len(flowerbed)):
        if flowerbed[i] == 0:
            left = (i == 0) or (flowerbed[i-1] == 0)
            right = (i == len(flowerbed)-1) or (flowerbed[i+1] == 0)

            if left and right:
                flowerbed[i] = 1
                count += 1

    return count >= k


flowerbed = list(map(int, input().split()))
k = int(input())

print(canPlaceFlowers(flowerbed, k))

def is_path_crossing(moves):
    x = 0
    y = 0

    visited = set()
    visited.add((0, 0))

    for m in moves:
        if m == 'R':
            x += 1
        elif m == 'L':
            x -= 1
        elif m == 'U':
            y += 1
        elif m == 'D':
            y -= 1

        if (x, y) in visited:
            return True

        visited.add((x, y))

    return False


moves = input()
print(is_path_crossing(moves))

def Median(nums):
    a = nums[:]

    for i in range(5):
        for j in range(4):
            if a[j] > a[j+1]:
                a[j], a[j+1] = a[j+1], a[j]

    return a[2]

def findRadius(houses, heaters):
    houses.sort()
    heaters.sort()

    max_radius = 0

    for h in houses:
        min_dist = float('inf')

        for t in heaters:
            dist = abs(h - t)
            if dist < min_dist:
                min_dist = dist

        if min_dist > max_radius:
            max_radius = min_dist

    return max_radius


houses = list(map(int, input().split()))
heaters = list(map(int, input().split()))

print(findRadius(houses, heaters))