# -*- coding: utf-8 -*-
"""buổi7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-cut7K4a5EQGeu2d20_MY3dqfTua_sp
"""

def binary_search(arr, left, right, target):
    while left <= right:
        mid = (left + right) // 2

        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1

def count_occurrences(arr, x):
    count = 0
    for i in range(len(arr)):
        if arr[i] == x:
            count += 1
    return count

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                temp = arr[j]
                arr[j] = arr[j + 1]
                arr[j + 1] = temp
    return arr

def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        min_index = i
        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j

        temp = arr[i]
        arr[i] = arr[min_index]
        arr[min_index] = temp

    return arr

def most_frequent(arr):
    max_count = 0
    result = arr[0]

    for i in range(len(arr)):
        count = 0
        for j in range(len(arr)):
            if arr[i] == arr[j]:
                count += 1

        if count > max_count:
            max_count = count
            result = arr[i]

    return result, max_count

def count_pairs(arr, X):
    count = 0
    n = len(arr)

    for i in range(n):
        for j in range(i + 1, n):
            if arr[i] + arr[j] == X:
                count += 1

    return count

def flatten_list(arr):
    result = []
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            result.append(arr[i][j])
    return result

def longest_increasing_subsequence(nums):
    n = len(nums)
    dp = [1] * n

    for i in range(n):
        for j in range(i):
            if nums[i] > nums[j]:
                dp[i] = max(dp[i], dp[j] + 1)

    return max(dp)

def min_interval(intervals, queries):
    result = []

    for q in queries:
        min_len = float('inf')

        for interval in intervals:
            l = interval[0]
            r = interval[1]

            if l <= q <= r:
                length = r - l + 1
                if length < min_len:
                    min_len = length

        if min_len == float('inf'):
            result.append(-1)
        else:
            result.append(min_len)

    return result

def count_smaller(nums):
    n = len(nums)
    result = []

    for i in range(n):
        count = 0
        for j in range(i + 1, n):
            if nums[j] < nums[i]:
                count += 1
        result.append(count)

    return result

def max_subarray_mod(nums, m):
    n = len(nums)
    max_value = 0

    for i in range(n):
        current_sum = 0
        for j in range(i, n):
            current_sum += nums[j]
            value = current_sum % m
            if value > max_value:
                max_value = value

    return max_value

def count_word(sentence, keyword):
    count = 0
    n = len(sentence)
    m = len(keyword)

    for i in range(n - m + 1):
        if sentence[i:i+m] == keyword:
            count += 1

    return count

def sort_phrases():
    A = input()
    B = input()
    C = input()
    D = input()
    arr = [
        ("A", A),
        ("B", B),
        ("C", C),
        ("D", D)
    ]
    arr.sort(key=lambda x: x[1])
    for item in arr:
        print(item[0], end=" ")

def longest_harmonious(arr):
    max_len = 0
    for i in range(len(arr)):
        count1 = 0
        count2 = 0
        for j in range(len(arr)):
            if arr[j] == arr[i]:
                count1 += 1
            if arr[j] == arr[i] + 1:
                count2 += 1
        if count1 > 0 and count2 > 0:
            if count1 + count2 > max_len:
                max_len = count1 + count2
    return max_len

def find_number_7():
    n = int(input())
    arr = list(map(int, input().split()))
    positions = []
    for i in range(n):
        if arr[i] == 7:
            positions.append(i)
    if len(positions) == 0:
        print("Not found")
    else:
        for i in range(len(positions)-1, -1, -1):
            print(positions[i], end=" ")

def find_neighbors():
    n = int(input())
    arr = []
    for i in range(n):
        name = input()
        arr.append(name)
    for i in range(n):
        if arr[i] == "Nemo":
            if i == 0:
                print(arr[n-1] + " and " + arr[i+1])
            elif i == n-1:
                print(arr[i-1] + " and " + arr[0])
            else:
                print(arr[i-1] + " and " + arr[i+1])