# -*- coding: utf-8 -*-
"""buổi 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pcp4duQCVscNoMEJYi4FBOewx2CIDd3
"""

class Cylinder:
    def __init__(self, r, h):
        self.r = r
        self.h = h
        self.pi = 3.14

    def surface_area(self):
        return 2 * self.pi * self.r * self.r + 2 * self.pi * self.r * self.h

    def volume(self):
        return self.pi * self.r * self.r * self.h


r, h = map(float, input().split())

c = Cylinder(r, h)

print(f"{c.surface_area():.2f} {c.volume():.2f}")

class Cylinder:
    def __init__(self, r, h):
        self.r = r
        self.h = h
        self.pi = 3.14

    def surface_area(self):
        return 2 * self.pi * self.r * self.r + 2 * self.pi * self.r * self.h

    def volume(self):
        return self.pi * self.r * self.r * self.h


r, h = map(float, input().split())

c = Cylinder(r, h)

print(f"{c.surface_area():.2f} {c.volume():.2f}")

import math

class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def is_origin(self):
        return self.x == 0 and self.y == 0

    def on_y_axis(self):
        return self.x == 0 and self.y != 0

    def on_x_axis(self):
        return self.y == 0 and self.x != 0

    def distance_to_origin(self):
        return math.sqrt(self.x*self.x + self.y*self.y)


x, y = map(float, input().split())

p = Point(x, y)

if p.is_origin():
    print("La goc toa do")
elif p.on_y_axis():
    print("Nam tren truc tung")
elif p.on_x_axis():
    print("Nam tren truc hoanh")
else:
    print("Khong nam tren truc nao")

print(f"{p.distance_to_origin():.2f}")

class Calculator:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def add(self):
        return self.a + self.b

    def subtract(self):
        return self.a - self.b

    def product(self):
        return self.a * self.b

    def divide(self):
        if self.b != 0:
            return self.a / self.b
        return "Khong chia duoc"

    def power(self):
        return self.a ** self.b

    def mod(self):
        if self.b != 0:
            return self.a % self.b
        return "Khong chia duoc"

    def set_numbers(self, a, b):
        self.a = a
        self.b = b


a, b = map(float, input().split())
cal = Calculator(a, b)

while True:
    print("1.Add 2.Sub 3.Mul 4.Div 5.Pow 6.Mod 7.Set")
    choice = input()

    if choice == "1":
        print(cal.add())
    elif choice == "2":
        print(cal.subtract())
    elif choice == "3":
        print(cal.product())
    elif choice == "4":
        print(cal.divide())
    elif choice == "5":
        print(cal.power())
    elif choice == "6":
        print(cal.mod())
    elif choice == "7":
        a, b = map(float, input().split())
        cal.set_numbers(a, b)

    exit_q = input("Ban co muon thoat? ")
    if exit_q in ["yes", "YES", "Yes"]:
        break

class ShoppingCart:
    def __init__(self):
        self.items = []

    def add(self, name, price):
        product = {"name": name, "price": price}
        self.items.append(product)

    def remove(self, name):
        for item in self.items:
            if item["name"] == name:
                self.items.remove(item)
                break

    def is_empty(self):
        return len(self.items) == 0

    def total(self):
        s = 0
        for item in self.items:
            s += item["price"]
        return s

    def show(self):
        for item in self.items:
            print(item["name"], item["price"])

    def clear(self):
        self.items = []


cart = ShoppingCart()

while True:
    print("2.Add 3.Remove 4.CheckEmpty 5.Total 6.Show 7.Clear")
    choice = input()

    if choice == "2":
        name = input()
        price = float(input())
        cart.add(name, price)

    elif choice == "3":
        name = input()
        cart.remove(name)

    elif choice == "4":
        print(cart.is_empty())

    elif choice == "5":
        print(cart.total())

    elif choice == "6":
        cart.show()

    elif choice == "7":
        cart.clear()

    exit_q = input("Co muon thoat khong? ")
    if exit_q == "yes":
        break

class Rectangle:
    def __init__(self, w, h):
        self.w = w
        self.h = h

    def area(self):
        return self.w * self.h

    def perimeter(self):
        return 2 * (self.w + self.h)

    def scale(self, k):
        self.w = self.w * k
        self.h = self.h * k


w, h, k = map(float, input().split())

r = Rectangle(w, h)
r.scale(k)

print(f"{r.area():.2f} {r.perimeter():.2f}")

def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a


class Fraction:
    def __init__(self, num, den):
        if den < 0:
            num = -num
            den = -den

        g = gcd(abs(num), abs(den))
        self.num = num // g
        self.den = den // g

    def add(self, other):
        n = self.num * other.den + other.num * self.den
        d = self.den * other.den
        return Fraction(n, d)

    def sub(self, other):
        n = self.num * other.den - other.num * self.den
        d = self.den * other.den
        return Fraction(n, d)

    def mul(self, other):
        return Fraction(self.num * other.num, self.den * other.den)

    def div(self, other):
        return Fraction(self.num * other.den, self.den * other.num)

    def __str__(self):
        return str(self.num) + "/" + str(self.den)


a, b, op, c, d = input().split()
a = int(a)
b = int(b)
c = int(c)
d = int(d)

f1 = Fraction(a, b)
f2 = Fraction(c, d)

if op == "+":
    print(f1.add(f2))
elif op == "-":
    print(f1.sub(f2))
elif op == "*":
    print(f1.mul(f2))
elif op == "/":
    print(f1.div(f2))

class BankAccount:
    def __init__(self, owner, balance):
        self.owner = owner
        self.balance = balance

    def deposit(self, x):
        self.balance += x

    def withdraw(self, x):
        if x <= self.balance:
            self.balance -= x

    def __str__(self):
        return self.owner + ": " + str(self.balance)


owner, bal = input().split()
bal = float(bal)

acc = BankAccount(owner, bal)

n = int(input())

for i in range(n):
    parts = input().split()
    if parts[0] == "DEPOSIT":
        acc.deposit(float(parts[1]))
    elif parts[0] == "WITHDRAW":
        acc.withdraw(float(parts[1]))

print(f"{acc.balance:.2f}")

class Student:
    def __init__(self, name):
        self.name = name
        self.scores = []

    def add_score(self, subject, score):
        self.scores.append(score)

    def avg(self):
        total = 0
        for s in self.scores:
            total += s
        return total / len(self.scores)

    def rank(self):
        a = self.avg()
        if a >= 8:
            return "Excellent"
        elif a >= 6.5:
            return "Good"
        elif a >= 5:
            return "Average"
        else:
            return "Poor"


name = input()
n = int(input())

st = Student(name)

for i in range(n):
    subject, score = input().split()
    st.add_score(subject, float(score))

print(f"{st.name} {st.avg():.2f} {st.rank()}")

class Book:
    def __init__(self, title, author, year):
        self.title = title
        self.author = author
        self.year = year


class Library:
    def __init__(self):
        self.books = []

    def add(self, book):
        self.books.append(book)

    def count_by_author(self, name):
        count = 0
        for b in self.books:
            if b.author == name:
                count += 1
        return count

    def find_by_year(self, y):
        count = 0
        for b in self.books:
            if b.year == y:
                count += 1
        return count


lib = Library()

n = int(input())

for i in range(n):
    line = input()

    if line.startswith("ADD"):
        data = line[4:]
        title, author, year = data.split(";")
        book = Book(title, author, int(year))
        lib.add(book)

    elif line.startswith("COUNTYEAR"):
        y = int(line.split()[1])
        print(lib.find_by_year(y))

    elif line.startswith("COUNT"):
        name = line.split()[1]
        print(lib.count_by_author(name))

import math

def cross(u, v):
    return [
        u[1]*v[2] - u[2]*v[1],
        u[2]*v[0] - u[0]*v[2],
        u[0]*v[1] - u[1]*v[0]
    ]

def dot(u, v):
    return u[0]*v[0] + u[1]*v[1] + u[2]*v[2]

def length(v):
    return math.sqrt(dot(v, v))


A = list(map(float, input().split()))
B = list(map(float, input().split()))
C = list(map(float, input().split()))
D = list(map(float, input().split()))

AB = [B[i] - A[i] for i in range(3)]
AC = [C[i] - A[i] for i in range(3)]
BC = [C[i] - B[i] for i in range(3)]
BD = [D[i] - B[i] for i in range(3)]

n1 = cross(AB, AC)
n2 = cross(BC, BD)

cos_phi = abs(dot(n1, n2)) / (length(n1) * length(n2))
phi = math.degrees(math.acos(cos_phi))

print(f"{phi:.2f}")

class ComplexNumber:
    def __init__(self, real, imag):
        self.real = real
        self.imag = imag

    def multiply(self, other):
        real_part = self.real * other.real - self.imag * other.imag
        imag_part = self.real * other.imag + self.imag * other.real
        return ComplexNumber(real_part, imag_part)


a1, b1 = map(float, input().split())
a2, b2 = map(float, input().split())

c1 = ComplexNumber(a1, b1)
c2 = ComplexNumber(a2, b2)

result = c1.multiply(c2)

print(result.real, result.imag)

import math

class Triangle:
    def __init__(self, e1, e2, e3):
        self.e1 = e1
        self.e2 = e2
        self.e3 = e3

    def getArea(self):
        if self.e1 + self.e2 <= self.e3 or \
           self.e1 + self.e3 <= self.e2 or \
           self.e2 + self.e3 <= self.e1:
            return -1

        s = (self.e1 + self.e2 + self.e3) / 2
        area = math.sqrt(s*(s-self.e1)*(s-self.e2)*(s-self.e3))
        return area


a, b, c = map(int, input().split())

t = Triangle(a, b, c)
area = t.getArea()

if area == -1:
    print("invalid")
else:
    print(f"{area:.2f}")